steps:
  # Step 1: Authenticate Docker với Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Authenticate Docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker ${LOCATION}-docker.pkg.dev

  # Step 2: Build Docker image với commit hash và latest
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      - 'build'
      - '-t'
      - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY}/${REPO_NAME}-${_ENVIRONMENT}:$SHORT_SHA'
      - '-t'
      - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY}/${REPO_NAME}-${_ENVIRONMENT}:latest'
      - '.'

  # Step 3: Push cả hai tag lên Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args:
      - 'push'
      - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY}/${REPO_NAME}-${_ENVIRONMENT}:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Latest Tag'
    args:
      - 'push'
      - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY}/${REPO_NAME}-${_ENVIRONMENT}:latest'

  # Step 4: Deploy ứng dụng lên Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    args:
      - 'run'
      - 'deploy'
      - '${REPO_NAME}-${_ENVIRONMENT}'
      - '--image=${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY}/${REPO_NAME}-${_ENVIRONMENT}:$SHORT_SHA'
      - '--region=${LOCATION}'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY}/${REPO_NAME}-${_ENVIRONMENT}:$SHORT_SHA'
  - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY}/${REPO_NAME}-${_ENVIRONMENT}:latest'
